name: user-service

replicaCount: 1

image:
  repository: tejaacr.azurecr.io/user-service
  tag: latest

container:
  name: user-container
  port: 8080

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpu: 50
