name: CI Build Pipeline

on:
  push:
    branches:
      - develop
      - qa
      - staging
      - main

env:
  ACR_NAME: tejaacr

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login ACR
      run: az acr login --name $ACR_NAME

########################################
# USER SERVICE
########################################

    - name: Build & Push User Service
      working-directory: microservices/user-service
      run: |
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/user-service:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/user-service:${{ github.sha }}

########################################
# ORDER SERVICE
########################################

    - name: Build & Push Order Service
      working-directory: microservices/order-service
      run: |
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/order-service:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/order-service:${{ github.sha }}

########################################
# PAYMENT SERVICE
########################################

    - name: Build & Push Payment Service
      working-directory: microservices/payment-service
      run: |
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/payment-service:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/payment-service:${{ github.sha }}

########################################
# SPRINGBOOT MONOLITH
########################################

    - name: Build & Push SpringBoot App
      run: |
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/aksdemo:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/aksdemo:${{ github.sha }}
