name: Deploy PreProd Environments

on:
  workflow_run:
    workflows: ["CI Build Pipeline"]
    types:
      - completed

env:
  ACR_NAME: tejaacr
  AKS_CLUSTER_NAME: teja-aks-cluster
  AKS_RESOURCE_GROUP: teja-devops-rg

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev,qa,staging]

    steps:
    - uses: actions/checkout@v3

    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connect AKS
      run: |
        az aks get-credentials \
          --resource-group $AKS_RESOURCE_GROUP \
          --name $AKS_CLUSTER_NAME \
          --overwrite-existing

    - name: Deploy to ${{ matrix.env }}
      run: |
        SHA=${{ github.event.workflow_run.head_sha }}
        NAMESPACE=${{ matrix.env }}

    
        echo "Deploying to namespace: $NAMESPACE"
        ###################################
        # Create namespace if not exists
        ###################################
        kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -

        ###################################
        # Deploy using HELM
        ###################################

        # USER SERVICE
        helm upgrade --install user-service ./helm/user-service \
          -n $NAMESPACE \
          -f ./helm/user-service/values-$NAMESPACE.yaml \
          --set image.tag=$SHA

        # ORDER SERVICE
        helm upgrade --install order-service ./helm/order-service \
          -n $NAMESPACE \
          -f ./helm/order-service/values-$NAMESPACE.yaml \
          --set image.tag=$SHA

        # PAYMENT SERVICE
        helm upgrade --install payment-service ./helm/payment-service \
          -n $NAMESPACE \
          -f ./helm/payment-service/values-$NAMESPACE.yaml \
          --set image.tag=$SHA

        # MONOLITH #
        helm upgrade --install springboot-app ./helm/monolith \
          -n $NAMESPACE \
          -f ./helm/monolith/values-$NAMESPACE.yaml \
          --set image.tag=$SHA

        kubectl apply -f ingress/ingress-$NAMESPACE.yaml -n $NAMESPACE
        
        
        
