name: Deploy PreProd Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        required: true
        default: "dev"
env:
  ACR_NAME: tejaacr
  AKS_CLUSTER_NAME: teja-cluster
  AKS_RESOURCE_GROUP: teja-rg

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev,qa,staging]

    steps:
    - uses: actions/checkout@v3
    
    - name: Login Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connect AKS
      run: |
        az aks get-credentials \
          --resource-group $AKS_RESOURCE_GROUP \
          --name $AKS_CLUSTER_NAME \
    
    - name: Deploy to ${{ matrix.env }}
      run: |
        set -e
    
        SHA=${{ github.event.workflow_run.head_sha }}
        NAMESPACE=${{ matrix.env }}
    
        echo "🚀 Deploying to namespace: $NAMESPACE"
    
        kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    
        helm dependency update ./helm/user-service
        helm dependency update ./helm/order-service
        helm dependency update ./helm/payment-service
        helm dependency update ./helm/monolith
    
        ###################################
        # DEPLOY USER SERVICE
        ###################################
        helm upgrade --install user-service ./helm/user-service \
          --namespace $NAMESPACE \
          -f ./helm/values-$NAMESPACE.yaml \
          --set image.tag=$SHA
    
        ###################################
        # DEPLOY ORDER SERVICE
        ###################################
        helm upgrade --install order-service ./helm/order-service \
          --namespace $NAMESPACE \
          -f ./helm/values-$NAMESPACE.yaml \
          --set image.tag=$SHA
    
        ###################################
        # DEPLOY PAYMENT SERVICE
        ###################################
        helm upgrade --install payment-service ./helm/payment-service \
          --namespace $NAMESPACE \
          -f ./helm/values-$NAMESPACE.yaml \
          --set image.tag=$SHA
    
        ###################################
        # DEPLOY MONOLITH
        ###################################
        helm upgrade --install springboot-app ./helm/monolith \
          --namespace $NAMESPACE \
          -f ./helm/values-$NAMESPACE.yaml \
          --set image.tag=$SHA
    
        ###################################
        # VERIFY
        ###################################
        kubectl rollout status deployment/user-service -n $NAMESPACE
        kubectl rollout status deployment/order-service -n $NAMESPACE
        kubectl rollout status deployment/payment-service -n $NAMESPACE
        kubectl rollout status deployment/springboot-app -n $NAMESPACE
    
        helm list -n $NAMESPACE
