name: Build and Deploy Applications to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: tejaacr
  AKS_CLUSTER_NAME: teja-aks-cluster
  AKS_RESOURCE_GROUP: teja-devops-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    # Login Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to ACR
    - name: Login to Azure Container Registry
      run: az acr login --name $ACR_NAME



################################################
# BUILD USER SERVICE
################################################

    - name: Build User Service
      run: |
        cd microservices/user-service
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/user-service:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/user-service:${{ github.sha }}

################################################
# BUILD ORDER SERVICE
################################################

    - name: Build Order Service
      run: |
        cd microservices/order-service
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/order-service:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/order-service:${{ github.sha }}

################################################
# BUILD PAYMENT SERVICE
################################################

    - name: Build Payment Service
      run: |
        cd microservices/payment-service
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/payment-service:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/payment-service:${{ github.sha }}

################################################
# BUILD MONOLITH SPRING BOOT APP
################################################

    - name: Build SpringBoot Monolith
      run: |
        mvn clean package -DskipTests
        docker build -t $ACR_NAME.azurecr.io/aksdemo:${{ github.sha }} .
        docker push $ACR_NAME.azurecr.io/aksdemo:${{ github.sha }}
################################################
# CONNECT AKS
################################################

    - name: Set AKS Context
      run: |
        az aks get-credentials \
          --resource-group $AKS_RESOURCE_GROUP \
          --name $AKS_CLUSTER_NAME \
          --overwrite-existing

################################################
# DEPLOY APPLICATIONS
################################################

    - name: Deploy to AKS
      run: |
        kubectl set image deployment/springboot-app springboot-container=$ACR_NAME.azurecr.io/aksdemo:${{ github.sha }}

        kubectl set image deployment/user-service user-container=$ACR_NAME.azurecr.io/user-service:${{ github.sha }}

        kubectl set image deployment/order-service order-container=$ACR_NAME.azurecr.io/order-service:${{ github.sha }}

        kubectl set image deployment/payment-service payment-container=$ACR_NAME.azurecr.io/payment-service:${{ github.sha }}

        kubectl rollout status deployment/springboot-app
        kubectl rollout status deployment/user-service
        kubectl rollout status deployment/order-service
        kubectl rollout status deployment/payment-service
